version: "3.7"

services:

    #Api
    api:
        image: ghcr.io/valerra45/api:main
        container_name: 'api'
        ports:
            - "5000:80"
            - "5001:443"
        links:
            - postgres    
        depends_on:
            - postgres
    #IS4
    identity-server:
        image: ghcr.io/valerra45/identityserver:main
        container_name: 'identity-server'
        ports:
            - "10000:80"
            - "10001:443"
        links:
            - postgres    
        depends_on:
            - postgres


    #Db
    postgres:
        restart: unless-stopped
        image: "postgres"
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=postgresdb
        ports: 
            - "5432:5432"
        volumes:
            - database-data:/var/lib/postgresql/data/

    #DbAdmin
    pgadmin:
        restart: unless-stopped
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "16543:80"
        volumes:
            - pgadmin:/root/.pgadmin 
        depends_on:
            - postgres 
    
    #RabbitMQ
    message-broker:
        image: rabbitmq:3-management
        restart: always
        hostname: "rabbitmq"
        labels:
            NAME: "rabbitmq"
        ports:
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "25672:25672"
            - "15671:15671"
            - "15672:15672"
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq

volumes:
    database-data:
    pgadmin:
    rabbitmq-data:          
