name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the IdentityServer Docker image
      run: docker build . --file src/Task.Identity/Task.Identity.WebHost/Dockerfile --tag identityserver:dev
    - name: Build the Api Docker image
      run: docker build . --file src/Task.Api/Task.Api.WebHost/Dockerfile --tag api:dev
