name: Docker Image CI

on:
   push:
    branches: [ main ]

env:
  IMAGE_NAME_IDENTITY: identityserver
  IMAGE_NAME_API: api
  IMAGE_NAME_GW: gw
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    
    - uses: actions/checkout@v3
    
    - name: Build the IdentityServer Docker image
      run: docker build . --file src/Task.Identity/Task.Identity.WebHost/Dockerfile --tag $IMAGE_NAME_IDENTITY
      
    - name: Push IdentityServer image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME_IDENTITY

        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        docker tag $IMAGE_NAME_IDENTITY $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
      
    - name: Build the Api Docker image
      run: docker build . --file src/Task.Api/Task.Api.WebHost/Dockerfile --tag $IMAGE_NAME_API

    - name: Push Api image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME_API

        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        docker tag $IMAGE_NAME_API $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION

    - name: Build the Gw Docker image
      run: docker build . --file src/Task.ApiGw/Tasks.Ocelot.WebHost/Dockerfile --tag $IMAGE_NAME_GW
      
    - name: Push Gw image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME_GW

        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        docker tag $IMAGE_NAME_GW $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION 
      
